--COMENTARIOS
/*
	mas de una línea de comentario
*/
--ESTO SON CONSULTAS BASICAS
--DEVUELVEN TODAS LAS COLUMNAS Y TODAS LAS FILAS DE UNA TABLA
select * from emp
select * from dept
--TAMBIEN PODEMOS ESCRIBIR CONSULTAS INDICANDO LAS COLUMNAS
--QUE DESEAMOS RECUPERAR DE LA TABLA
select apellido, oficio, salario from emp
--ORDENACION DE DATOS.  ESTO SIEMPRE IRA AL FINAL DE LAS CONSULTAS
--order by columna ASC/DESC
--ORDENAMOS LOS EMPLEADOS POR SU APELLIDO DE FORMA ASCENDENTE
select * from EMP order by apellido asc
--ORDENAMOS LOS EMPLEADOS POR SU APELLIDO DE FORMA DESCENDENTE
select * from EMP order by apellido desc
--FILTRADO DE DATOS: where
--SOLAMENTE TENDREMOS UN where EN LA CONSULTA Y SE UTILIZAN 
--OPERADORES DE COMPARACION PARA COMPARAR CON LOS DATOS.
/*
OPERADORES DE COMPARACION
	> mayor
	>= mayor o igual
	< menor
	<= menor o igual 
	= igual
	<> distinto
*/
--TODO LO QUE NO SEA UN NUMERO SE COMPARA CON COMILLAS SIMPLES
--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 20
select * from emp where dept_no = 20
--MOSTRAR TODOS LOS EMPLEADOS QUE TENGAN OFICIO ANALISTA
select * from emp where oficio = 'analista'
--SI NECESITAMOS MAS DE UN FILTRO SE UTILIZAN LOS OPERADORES RELACIONALES
/*
OPERADORES RELACIONALES
	AND: TODOS LOS FILTROS DEBEN CUMPLIRSE 
	OR: MUESTRA DATOS DE CADA FILTRO
	NOT: NEGACION DE UNA CONSULTA
*/
--MOSTRAR LOS EMPLEADOS QUE TENGAN OFICIO ANALISTA Y QUE 
--COBREN MAS DE 300000
select * from emp where oficio = 'ANALISTA' and salario > 300000
--MOSTRAR TODOS LOS EMPLEADOS QUE SEAN DEL DEPARTAMENTO 10 Y DEL DEPARTAMENTO 30
select * from emp where dept_no = 10 or dept_no = 30
--EL NOT NUNCA LO VAMOS A UTILIZAR, RALENTIZA UNA CONSULTA
--MOSTRAR TODOS LOS EMPLEADOS QUE NO SEAN DIRECTOR
select * from emp where NOT oficio = 'DIRECTOR'
--SIEMPRE UTILIZAREMOS OPERADORES PARA LAS CONSULTAS
select * from emp where oficio <> 'DIRECTOR'
--OTROS OPERADORES DE COMPARACION
--between: BUSCA ENTRE DOS DATOS INCLUYENDO LA BUSQUEDA
--MOSTRAR TODOS LOS EMPLEADOS CUYO SALARIO SEA ENTRE 208.000 y 300.000
select * from emp where salario between 208000 and 300000
--TAMBIEN PODEMOS UTILIZAR LA CONSULTA CON OPERADORES TRADICIONALES
select * from emp where salario >= 208000 and salario <= 300000
--OPERADOR IN: BUSCA COINCIDENCIAS CON IGUALDAD DENTRO DE UN MISMO CAMPO
--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10 y DEL 20 y DEL 30, 80, 90, 120
select * from emp where dept_no = 10 or dept_no = 20 or dept_no = 30
or dept_no = 80 or dept_no = 90 or dept_no = 120
--operador in (valor1, valor2, valor3)
select * from emp where dept_no in (10, 20, 30, 80, 90, 120)
--OPERADOR NOT IN: RECUPERA LOS DATOS CONTRARIOS A LA COMPARACION DE UN
--MISMO CAMPO
--MOSTRAR TODOS LOS EMPLEADOS QUE NO SEAN DEL DEPARTAMENTO 10 Y DEL 20
select * from emp where dept_no not in (10, 20)
--ESTO ES UNA NEGACION, NUNCA UTILIZAR
select * from emp where not dept_no  in (10, 20)
--OPERADOR LIKE
--BUSCA COINCIDENCIAS EN TEXTO DENTRO DE UNA CADENA DE CARACTERES
--  _ UN CARACTER CUALQUIERA
--  ? UN CARACTER TIPO NUMERO
--  % CUALQUIER CARACTER Y LONGITUD
--SE UTILIZA PARA BUSQUEDAS EN TEXTOS
--MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO COMIENCE CON A
select * from EMP where APELLIDO like 'A%'
--MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO CONTENGA LA LETRA A
select * from EMP where APELLIDO like '%A%'
--MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO SEA DE 4 LETRAS
select * from EMP where APELLIDO like '____'
--CAMPOS CALCULADOS
--SON CAMPOS QUE SE CALCULAN EN LA CONSULTA EN BASE A OTRAS COLUMNAS
--LAS COLUMNAS SE CALCULAN Y NO EXISTEN EN LA TABLA
--DEBEMOS INDICAR UN NAME A LOS CAMPOS CALCULADOS
--NO PODEMOS TENER NOMBRES DE COLUMNAS REPETIDOS EN LAS CONSULTAS
--NECESITAMOS MOSTRAR EL SALARIO + COMISION DE LOS EMPLEADOS
select APELLIDO, SALARIO, COMISION, SALARIO + COMISION AS TOTAL from EMP
--LOS CAMPOS CALCULADOS NO PODEMOS UTILIZARLOS EN UN WHERE CON SU ALIAS
--SI DESEAMOS FILTRAR LOS DATOS DE UN CAMPO CALCULADO, TENDREMOS QUE 
--VOLVER A REALIZAR EL CALCULO DENTRO DEL WHERE
--MOSTRAR LOS DATOS DE LOS EMPLEADOS CON SU SALARIO TOTAL (SALARIO + COMISION)
--PERO SOLAMENTE LOS QUE COBREN MAS DE 300.000 EN SU SALARIO TOTAL
select APELLIDO, SALARIO, COMISION, SALARIO + COMISION AS TOTAL from EMP
where SALARIO + COMISION > 300000
--TAMBIEN PODEMOS UTILIZAR CAMPOS CALCULADOS CON TIPOS DE DATO TEXTO
--PARA UNIR DOS TEXTOS SE UTILIZA EL SIMBOLO +
--MOSTRAR EL APELLIDO Y OFICIO EN UNA COLUMNA COMO DESCRIPCION DE LOS EMPLEADOS
select APELLIDO + ' ' + OFICIO AS DESCRIPCION from EMP
--CLAUSULA DISTINCT
--ELIMINA RESULTADOS REPETIDOS DENTRO DE LA CONSULTA
--SE UTILIZA PARA MOSTRAR DATOS DE UN GRUPO
--MOSTRAR TODOS LOS OFICIOS DE LOS EMPLEADOS
select OFICIO from EMP
--MOSTRAR LOS DIFERENTES OFICIOS DE LOS EMPLEADOS
select DISTINCT OFICIO from EMP
--CONSULTAS DE AGRUPACION
--CONTAR EL NUMERO DE REGISTROS DE LA TABLA DEPARTAMENTOS
select COUNT(*) as REGISTROS from DEPT
--PODEMOS COMBINAR DIFERENTES FUNCIONES EN LA MISMA CONSULTA
--MOSTRAR EL NUMERO DE PERSONAS, EL MAXIMO SALARIO Y EL MINIMO DE LA TABLA EMP
select COUNT(*) as PERSONAS, MAX(SALARIO) AS MAXIMO_SALARIO
, MIN(SALARIO) AS MINIMO_SALARIO from EMP
--LAS CONSULTAS PUEDEN REALIZAR AGRUPANDO POR ALGUN CAMPO/S DE LA TABLA
--EJEMPLO: QUEREMOS SABER EL NUMERO DE PERSONAS QUE REALIZAN CADA OFICIO
--SE UTILIZA UNA INSTRUCCION LLAMADA GROUP BY
--TRUCO: UTILIZAR GROUP BY POR CADA COLUMNA DEL SELECT QUE NO SEA UNA FUNCION
select COUNT(*) as PERSONAS, OFICIO from EMP
group by OFICIO
--PODEMOS AGRUPAR POR MAS DE UN CAMPO
--MOSTRAR EL MAXIMO SALARIO POR CADA OFICIO Y DEPARTAMENTO
select MAX(SALARIO) as MAXIMO_SALARIO, OFICIO, DEPT_NO from EMP
group by OFICIO, DEPT_NO
--SI DESEAMOS FILTRAR, UTILIZAMOS where ANTES DEL GROUP BY
--CONTAR EL NUMERO DE PERSONAS POR CADA OFICIO QUE SE DIERON DE ALTA
--EN LA EMPRESA DESPUES DE 1987
select COUNT(*) AS PERSONAS, OFICIO from EMP
where FECHA_ALT >= '01/01/1987'
group by OFICIO

select TABLA1.CAMPO1, TABLA1.CAMPO2
, TABLA2.CAMPO1, TABLA2.CAMPO2
FROM TABLA1
INNER JOIN TABLA2
ON TABLA1.CAMPORELACIONADO = TABLA2.CAMPORELACIONADO

--MOSTRAR EL APELLIDO, EL OFICIO Y EL NOMBRE DE DEPARTAMENTO DE LOS EMPLEADOS
select EMP.APELLIDO, EMP.OFICIO
, DEPT.DNOMBRE
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO

--PODEMOS UTILIZAR WHERE PARA LAS CONSULTAS
--MOSTRAR EL APELLIDO Y LA LOCALIDAD DE LOS EMPLEADOS QUE 
--TRABAJEN EN EL DEPARTAMENTO DE VENTAS
select EMP.APELLIDO, DEPT.LOC
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
where DEPT.DNOMBRE = 'VENTAS'

--PODEMOS UTILIZAR GROUP BY CON ESTE TIPO DE CONSULTAS
--MOSTRAR LA SUMA SALARIAL DE LOS EMPLEADOS POR CADA LOCALIDAD
select SUM(EMP.SALARIO) AS SUMA_SALARIAL, DEPT.LOC
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
group by DEPT.LOC
--INSERTAR UN NUEVO DEPARTAMENTO DE INFORMATICA EN GIJON
INSERT INTO DEPT VALUES (50, 'INFORMATICA', 'GIJON')
select * from DEPT
--POR ENVIDIA, QUEREMOS ABRIR UN DEPARTAMENTO EN OVIEDO
--PERO NO SABEMOS DE QUE TODAVIA
INSERT INTO DEPT (DEPT_NO, LOC) VALUES (60, 'OVIEDO')
--QUEREMOS ELIMINAR EL DEPARTAMENTO DE GIJON
DELETE FROM DEPT WHERE LOC = 'GIJON'
--QUEREMOS ELIMINAR LOS DEPARTAMENTOS QUE TENGAN UN NOMBRE NULL
DELETE FROM DEPT WHERE DNOMBRE IS NULL

--EL DEPARTAMENTO DE BARCELONA SE TRASLADA ZARAGOZA
UPDATE DEPT SET LOC = 'ZARAGOZA'
WHERE LOC = 'BARCELONA'

--PODEMOS UTILIZAR VALORES EXISTENTES DE LAS TABLAS 
--AL REALIZAR UN SET.
--INCREMENTAR EL SALARIO DE TODOS LOS EMPLEADOS EN 1 
UPDATE EMP SET SALARIO = SALARIO + 1

--INCREMENTAR EL SALARIO DE LOS EMPLEADOS CON OFICIO DIRECTO EN 1 
UPDATE EMP SET SALARIO = SALARIO + 1
WHERE OFICIO = 'DIRECTOR'
